kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: reboot-coordinator
  name: reboot-coordinator
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reboot-coordinator
rules:
  - apiGroups:
      - ""
    resources:
      - "nodes"
      - "configmaps"
    verbs:
      - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reboot-coordinator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reboot-coordinator
subjects:
  - kind: ServiceAccount
    name: reboot-coordinator
    namespace: reboot-coordinator
